### ISSUE TITLE
Add Gaussian Blur support for u8 images

### ISSUE THREAD

**Issue by AS1100K** [kornia/kornia-rs#461]
Currently, the Gaussian Blur functionality is only implemented for `f32` images.

It would be beneficial to add support for `u8` images as well. This would enable broader usage scenarios and improve the usability of the Gaussian Blur functionality for typical image processing pipelines where `u8` images are common.

**Comment by gulshan-123** [comment]
Hi @AS1100K, I am new to kornia rust. I have read contributing guidelines and want to work on this issue.

**Comment by AS1100K** [comment]
Go ahead @gulshan-123

**Comment by gulshan-123** [comment]
Hi @AS1100K, I have opened a PR, please review

**Comment by afrdbaig7** [comment]
Hi I would like to take this issue
If there’s no one else currently assigned, could you please assign it to me
Thanks

**Comment by afrdbaig7** [comment]
@edgarriba 
Update: Finalized Fix for Issue #461
I’ve pushed the final implementation to add u8 support for gaussianblur (and boxblur for consistency).

Changes:
Generic API:
Updated gaussianblur and boxblur to be generic over the pixel type, exposing the existing multi-type support already implemented in separablefilter via FloatConversion.

Cleanup:
Removed the now-redundant gaussian_blur_u8 wrapper and updated benchmarks to use the unified generic API.

Testing:
Added a regression test to verify correct u8 gaussian blur behavior, including proper clamping. All existing tests pass, and benchmarks compile successfully.

**Comment by Nyx128** [comment]
Hi, i would like to try this issue if nobody is working on it. As i saw in the previous PRs, float conversion will only bottleneck performance so here is a list of things i will do:

- Add fixed-point Gaussian kernel generation .

- Implement a separable u8 convolution using widened accumulators (u32) and bit-shift normalization.

- Expose a new gaussian_blur_u8 API while keeping existing float paths unchanged.

- write tests to validate against the current f32 implementation within certain tolerances we can discuss upon.

I also plan to implement SIMD operations for this, after my initial working functions. I will try to benchmark and document improvements best i can.

Please let me know if my plan sounds reasonable.

**Comment by RakshithaKowlikar** [comment]
I've completed the box_blur optimization (merge pending) as discussed. I will be moving on to gaussian_blur for u8 that uses this. Would it be possible to assign this issue to me?

**Comment by AdityaShome** [comment]
As it is still not resolved, I have made a separate `gaussian_blur_u8` function, backed by a explicit `separable_filter_i16` engine, to completely bypass costly f32 conversions. This new path leverages quantized i16 kernels (normalized to 256) and i32 accumulators. Performance was enhanced by parallelizing execution with Rayon and restructuring loops to enable extensive SIMD auto vectorization. The result is bechmarked with a 2.1x speedup (277µs vs 600µs) over the generic implementation, all while ensuring correct edge handling via replicate padding. Should I proceed with it?

**Comment by Arijit-Sarkar03** [comment]
I'd like to implement this using fixed-point kernel quantization (i16 kernel, i32 accumulator) with Rayon row-parallelism, following the approach described by @Nyx128 in this thread. Can I be assigned?"
